### ISSUE TITLE
NullPointerException: on product/createorupdateproduct

### ISSUE THREAD

**Issue by NASWEEF** [navas-infobreez/-Customer-Diary-Server#11]
java.lang.NullPointerException: null

java.lang.NullPointerException: null

2020-10-20T11:07:43.413168+00:00 app[web.1]: 	at com.planet.customer.diary.customer_diary.service.impl.ProductPriceServiceImpl.mapProductPriceDTOToEntity(ProductPriceServiceImpl.java:26) ~[classes/:1.0]

2020-10-20T11:07:43.413169+00:00 app[web.1]: 	at com.planet.customer.diary.customer_diary.service.impl.ProductServiceImpl.mapDTOToProductEntity(ProductServiceImpl.java:62) ~[classes/:1.0]

2020-10-20T11:07:43.413169+00:00 app[web.1]: 	at com.planet.customer.diary.customer_diary.service.impl.ProductServiceImpl.createOrUpdateProduct(ProductServiceImpl.java:102) ~[classes/:1.0]

**Comment by navas-infobreez** [comment]
error due to null value check missing price list and chnaged lots in product create and update
